## Integrantes
- Alarcón Rodríguez Luis Guillermo
- Chávez Salgado Carlos Daniel
- Rodríguez Salas Carlos Oswaldo

# Tarea 2: Funciones y Objetos

Esta tarea ya no pretende ser minimalista por lo tanto se permite el uso de cualquier operador o función de Julia, **siempre y cuando no se requiera instalar paqueterías extra.** 

La fecha máxima de entrega es el jueves 7 de octubre a las 3pm. Tienen 2 días de cortecía (en realidad son tareas de una semana), así que igual que con la primera tarea, las tareas que se entreguen con retraso, no se calificarán (**no importa el motivo por el que no la entregaron**, para eso tienen 2 días extra). Intenten entregarla el martes 5 de octubre. 

Igual que la tarea anterior, se califica sobre 18 problemas. Si hacen los 19, el último no contará, aunque impresiona que lo hagan. 

Esta tarea ya tiene un poquito más de chiste, aunque creo que el salto no es gigante. 

## Funciones

[1] **(fácil)** Haz una función para calcular el área de: 

(i) un círculo de radio $r$

(ii) un rectángulo de lados $a$ y $b$

(iii) un polígono (no necesariamente regular) con vértices $\vec{p}_1, \vec{p}_2, \dots, \vec{p}_n$. 

Finalmente prueba tus funciones para varios casos (especialmente la del polígono). Por ejemplo, checa que calcule bien el área de un triángulo, un rectángulo y un pentágono. 

**hint:** Intenta pensar como resolver el último sin este hint, pero si te rindes, puedes revisar aquí una técnica muy buena: https://en.wikipedia.org/wiki/Shoelace_formula. 

**Nota:** Trata de que cada función quede en una sola línea de código. 

In [1]:
typeof([[1,2],[1,3],[3,4],[4,5]])

Vector{Vector{Int64}} (alias for Array{Array{Int64, 1}, 1})

In [2]:
area(r) = π * r^2 # Calcula el área de un círculo de radio r
area(a,b) = a * b # Calcula el área de un rectángulo de lados a y b
using LinearAlgebra
function area(vertices) # Calcula el área de un polígono de n lados por medio de la fórmula de Schoelace
    numeroLados = length(vertices)
    areafinal = 1/2 * abs(sum(*(vertices[i+1][1] + vertices[i][1], vertices[i+1][2] - vertices[i][2]) for i ∈ 1:(numeroLados-1)))
    areafinal += 1/2 * abs(sum(*(vertices[1][1] + vertices[numeroLados][1], vertices[1][2] - vertices[numeroLados][2])))
    return areafinal
end

area (generic function with 2 methods)

In [3]:
area([[0.0,0.0],[1.0,0.0],[0.0,1.0]])

0.5

[2] **(fácil)** Utilizando condicionales, haz una función que arroje la fuerza electrostática sobre una partícula de carga $q$ y posición $\vec{x}$ si en el origen hay una esfera de radio $1$ que tiene densidad de carga constante en la superficie. 

In [4]:
function fuerzaElectroEsfera(q::Real, σ::Real, x::Array) # Calcula la fuerza electrica que siente una carga de una esfera de radio 1
    if norm(x) < 1
        return 0, x
    end
    ϵ_0 = 8.85e-12
    F = q * σ / (ϵ_0 * (x ⋅ x))
    return F, x
end

fuerzaElectroEsfera (generic function with 1 method)

In [5]:
fuerzaElectroEsfera(5e-12,1,[3,4,1])

(0.021729682746631895, [3, 4, 1])

[3] **(fácil)** Utiliza la función que calcula el área de un polígono para calcular el área bajo la curva de una función estrictamente no negativa en un intervalo dado $[a,b]$. Para esto, obtén $n+1$ puntos equidistantes en ese intervalo ($[a, a+(b-a)/n, \dots, b]$) y con ellos obtén las coordenadas de los vértices del polígono que aproxima al área bajo la curva, $[a, 0], [a, f(a)], [a+(b-a)/n, f(a+(b-a)/n)], \dots, [b, f(b)], [b, 0]$ y finalmente calcula su área. 

In [6]:
function particion(a::Real, b::Real, n::Int64)
    w = [a]
    for i in (1:n)
        push!(w, a + i*((b-a)/n) )
    end
    w
end

particion (generic function with 1 method)

In [7]:
function evaluacion(g, a, b, n)
    g.(particion(a,b,n))
end

evaluacion (generic function with 1 method)

In [8]:
function vertices(x, y)
    z = []
    for i in (1:length(x))
        push!(z, [x[i],y[i]])
    end
    return z
end

vertices (generic function with 1 method)

In [9]:
function area_de_funciones(a1, b1, n1, f1)
    l = particion(a1, b1, n1)
    j = evaluacion(f1, a1, b1, n1)
    v = vertices(l,j)
    insert!(v, 1, [a1,0.0])
    push!(v, [b1,0.0])
    area(v)
end

area_de_funciones (generic function with 1 method)

In [10]:
area_de_funciones(0.0, 5.0, 100, exp)

147.44386889783777

[4] **(fácil)** Utilizando la función del ejercicio anterior, haz una función que calcule numéricamente la integral de una función cualquiera $f$ en un un intervalo $[a,b]$, aproximando con $n$ divisiones (que $n$ sea un argumento de la función, pero pre-fijado en 100). 

Prueba tu función con la función $sin$, $exp$, $x$, $x^4$ (checando sobre los intervalos que elijas que coincida aceptablemente el cálculo numérico con el analítico). 

In [11]:
area_n_100(a,b,f) = area_de_funciones(a, b, 100, f)

area_n_100 (generic function with 1 method)

In [12]:
funciones = [sin, exp, x -> x, x -> x^4]
[area_n_100(0.0, π, i) for i in funciones]

4-element Vector{Float64}:
  1.9998355038874436
 22.142513601804502
  4.934802200544679
 61.21413751120923

[5] **(dificultad media)** Cada segundo en una colonia de bacterias puede suceder para cada bacteria que: (a) la bacteria muera con probabilidad $r$, (b) que la bacteria se reproduzca (se duplica) con probabilidad $1-r$. Haz una función para estimar numéricamente la probabilidad de que la colonia sobreviva después de $t$ segundos si se comienza con una sola bacteria (la función depende de $r$ y de $t$. 

¿cuál es el número promedio de bacterias después de 10,20, 50,100, mil y 10mil segundos si $r = 0.01, 0.1, 0.2, 0.3, 0.5, 0.8$? 

¿A partir de qué valor de $r$ se observa que la colonia se extingue? 

## Advertencia
Para $r=0.01, 0.1, 0.2$ el código se traba para t grande, pues se crean demasiadas bacterias y al iterar sobre números muy grandes no funciona.

In [13]:
mutable struct Bacteria
    probMorir::Real
    probReproducir::Real
end
"""
Esta función calcula el número de bacterias después de t segundos, si las bacterias se extinguen antes de que llegue a t,
te dice en que tiempo se extinguen
"""
function probSobrevivir(r::Real,t::Real) 
    b = Bacteria(r,abs(1-r))
    tiempo = 0
    numBacterias = 1                        #numBacterias=1 pues crearemos una bacteria
    while tiempo < t && numBacterias > 0
        bacteriaux = 0
        i = 0
        while i < numBacterias
            testMuerte = rand()
            testReproduccion = rand()
            if testReproduccion < b.probReproducir
                bacteriaux += 1
            end
            if testMuerte < b.probMorir
             bacteriaux -= 1
            end
            i += 1
        end
        tiempo += 1
        numBacterias += bacteriaux
    end
    return numBacterias, tiempo
end

probSobrevivir

In [14]:
[probSobrevivir(0.01, t) for t in [10, 20]]

2-element Vector{Tuple{Int64, Int64}}:
 (942, 10)
 (869922, 20)

In [15]:
[probSobrevivir(0.1, t) for t in [10, 20]]

2-element Vector{Tuple{Int64, Int64}}:
 (520, 10)
 (184540, 20)

In [16]:
[probSobrevivir(0.2, t) for t in [10, 20]]

2-element Vector{Tuple{Int64, Int64}}:
 (108, 10)
 (6982, 20)

In [17]:
[probSobrevivir(0.3, t) for t in [10, 20, 50]]

3-element Vector{Tuple{Int64, Int64}}:
 (4, 10)
 (988, 20)
 (29508181, 50)

In [18]:
[probSobrevivir(0.5, t) for t in [10, 20, 50, 100, 1_000, 10_000]]

6-element Vector{Tuple{Int64, Int64}}:
 (0, 4)
 (0, 1)
 (0, 1)
 (0, 5)
 (0, 4)
 (0, 1)

In [19]:
[probSobrevivir(0.8, t) for t in [10, 20, 50, 100, 1_000, 10_000]]

6-element Vector{Tuple{Int64, Int64}}:
 (0, 2)
 (0, 2)
 (0, 3)
 (0, 2)
 (0, 2)
 (0, 2)

Las bacterias comienzan a extinguirse a partir de $r=0.5$

Para el siguiente código no hay advertencias

In [20]:
function poblacion(r::Real,t::Real) #numBacterias=1 pues crearemos una bacteria
    numBacterias::BigFloat = 1
    probsob::BigFloat=1-r
    for tiempo in 1:t
         numBacterias=numBacterias+((1-r)*numBacterias)-(r*numBacterias)  #La poblacion evoluciona de acuerdo a una distribucion binomial
         probsob=probsob*(1-r^(numBacterias)) 
    end
     return  println("Con una probabilidad de muerte de $(r) la poblacion promedio de la colonia despues de $(t) segundos es de $(numBacterias)
                       y la probabilidad de haber durado este tiempo es de $(probsob)")
end

 for t in [10, 20,50,100,1000,10000]
     for r in [0.01,0.1,0.2,0.3,0.5,0.8]
        poblacion(r,t)       
                                
    end                           #Se observa que a partir de r=0.5 la probabilidad de que la colonia sobreviva es practicamente nula y se extingue
end


Con una probabilidad de muerte de 0.01 la poblacion promedio de la colonia despues de 10 segundos es de 926.0872448090157552546456054853939142204577074200691163749888874515689115477549
                       y la probabilidad de haber durado este tiempo es de 0.9898914343766294077791623915055630888092630006646167001278852126480950707872784
Con una probabilidad de muerte de 0.1 la poblacion promedio de la colonia despues de 10 segundos es de 357.0467226624000330334576972290974591957720086678281883397896664204173863636499
                       y la probabilidad de haber durado este tiempo es de 0.88522497006394252433322624419781639248876531315927576303539181111698070075104
Con una probabilidad de muerte de 0.2 la poblacion promedio de la colonia despues de 10 segundos es de 109.9511627776000228881835937500021440521477374478522854943506019582340361047221
                       y la probabilidad de haber durado este tiempo es de 0.7260630810911474660859023168873483009623097480987537389661



[6] **(talachudo)** En la tarea anterior vimos que las letras con acentos son problemáticas, porque las registra como 2 símbolos, uno que se puede leer y uno que no. Lo mismo sucede con ¿, ñ, ¡, entre otros. Haz una función que de un texto en español con símbolos y acentos incómodos, lo pase a un texto en español que reconozca Unicode. 

In [58]:
caract = ["á","é","í","ó","ú","Á","É","Í","Ó","Ú","¿","ñ","Ñ","¡"]
caract1 = ["a","e","i","o","u","A","E","I","O","U","","n","N",""]
## Esta función nos indica los índices de nuestra String (el texto) donde hay algún caracter en español de los que vienen en 'caract'

function skip(x)                                   # x es el texto
    y = []
    for j in 1:length(caract)
        append!(y, findall(caract[j], x))          # cada iteración añade los índices que buscamos en un arreglo de rangos 
    end
    return sort!([y[i][1] for i in 1:length(y)])   # aquí obtenemos un arreglo de numeros (más fácil de trabajar)
    y
end
## Esta función nos va a dar un arreglo con los números del 1 hasta el numero de elmentos de nuestra String pero sin los índices que no queremos
## Los caracteres en español ocupan dos lugares en el String pero el segundo causa problemas con nuestra función final, por eso no los queremos tomar en cuenta

function array_bueno(x)                                 # x es String
    u = skip(x)
    v = [i for i in 1:(length(x) + length(u))]          # v es el arreglo con todos los números del 1 al numero de caracteres y se suma la longitud de u porque la función length() 
                                                        # cuenta a los caracteres en español como uno solo pero para nuestro caso necesitamos contar los espacios reales.     
    for j in 1:length(u)
        deleteat!(v, u[j] - (j-1) + 1)                  # aquí eliminamos los indices problematicos
    end
    v
end

# Esta función nos va a convertir nuestro texto (String) en un arreglo donde cada elemento de este es un caracter del texto, en orden 

function arreglos(x)                                   # x es el texto
    y = []
    for i in array_bueno(x)                            # i va a correr en el arreglo que obtuvimos anteriormente
        push!(y, "$(x[i])")                            # aquí se forma en arreglo
    end
    return y
end

## En esta función se analiza cada elemento del arreglo y si encuentra un caracter en español, lo cambia poe el correspondiente a Unicode

function espanol(x)                                     # x es un arreglo de caractéres
    for i in 1:length(x)
    for j in 1:length(caract)
        if x[i] == caract[j]
            deleteat!(x, i)                             # aquí borra el elemento en español
            insert!(x, i, caract1[j])                   # aquí lo sustituye
        else
            continue
        end
    end
    end
    return x
end

## Por último, componemos las dos últimas funciones para que ddado un x = texto(String) nos lo convierta en otro texto pero con todos los caracteres de Unicode

function traductor(x)
    prod(espanol(arreglos(x)))
end

# Ejemplo random
traductor("Holá a todás, las mucháchas dél mundó entérítú!!")

"Hola a todas, las muchachas del mundo enteritu!!"

In [59]:
# Ejemplo poema
traductor("Ni silencio, ni palabras: tu voz, sólo, sólo, hablándome.")

"Ni silencio, ni palabras: tu voz, solo, solo, hablandome."

[7] **(dificultad media)** Haz una función que dado un texto, regrese un arreglo con las palabras que contiene el texto ordenadas de la palabra más frecuente a la menos frecuente y también regrese un arreglo con el número de veces que aparece cada palabra. Asegúrate de eliminar los signos de puntuación. 

Prueba tu función con un par de textos "largos" (al menos que tenga unas mil palabras). 

Si quieres jugar un poco más, prueba con varios autores y con varios textos del mismo autor ¿Hay algo en común en todos? ¿hay algo particular de cada autor?

In [24]:
function frecuencia(g)
    a=split(g, " ")
    l=[]
    h=[]
    u=unique(a)
    for n ∈ 1:length(u)
         d=0
        for i ∈ 1:length(a)
        if u[n]==a[i]
            d+=1
            end
        end
    push!(h, d)
    end
    append!(l, [u[i], h[i]] for i ∈ 1:length(u))
    y=sort!(l, by = x -> x[2], rev=true)
    return y
end 
frecuencia("Haz una funcion que dado un texto regrese un arreglo con las palabras que contiene el texto ordenadas de la palabra mas frecuente a la menos frecuente y tambien regrese un arreglo con el numero de veces que aparece cada palabra Asegurate de eliminar los signos de puntuación" )

33-element Vector{Any}:
 Any["de", 4]
 Any["que", 3]
 Any["un", 3]
 Any["texto", 2]
 Any["regrese", 2]
 Any["arreglo", 2]
 Any["con", 2]
 Any["el", 2]
 Any["la", 2]
 Any["palabra", 2]
 Any["frecuente", 2]
 Any["Haz", 1]
 Any["una", 1]
 ⋮
 Any["menos", 1]
 Any["y", 1]
 Any["tambien", 1]
 Any["numero", 1]
 Any["veces", 1]
 Any["aparece", 1]
 Any["cada", 1]
 Any["Asegurate", 1]
 Any["eliminar", 1]
 Any["los", 1]
 Any["signos", 1]
 Any["puntuación", 1]

[8] **(dificil)** Gráficas con símbolos. Una forma de graficar es simplemente imprimir una matriz con símbolos. Usando la función print y el símbolo \n para saltar linea, puedes imprimir adecuadamente los símbolos para dibujar una función grafica_con_simbolos(p, x, y), por ejemplo, poniendo el símbolo "x" para cuando un punto está ocupado y el símbolo " " para cuando no. Usando esta idea haz una función que grafique los puntos de un arreglo de puntos $[\vec{p}_1, \dots, \vec{p}_n]$, dado los límites en el eje $x$ y $y$. 

Utiliza esta función para graficar el histograma (el número de veces que aparece cada palabra) del ejercicio anterior. 

También utilizala para graficar el número de bacterias promedio como función del tiempo del ejercicio 5. 

Nota: busca sobre la ley de Zipf si quieres saber más sobre ese resultado. 

[9] **(dificultad media)** Haz una función que encuentre cualquier número (como tu fecha de cumpleaños ddmmaaaa) dentro de las primeras  6,020,601  de cifras de  𝜋 . Para esto tendrás que poner la precisión de los BigFloat en  20,000,000 . Si utilizas cadenas, recuerda que la primera cifra es 3 y la segunda es 1, no ".". (mi cumpleaños completo está entre la cifra 5712844 y 5712851). ¿Cuándo nací?

In [25]:
function número_en_π(N::Int)
    cadena_N = string(N) #Convertimos el entero en una cadena
    setprecision(BigFloat, 20_000_000) do #Cambios la precisión
        cifras_π = deleteat!([i for i ∈ string(BigFloat(π))], 2) #Eliminamos el "."
        for i ∈ 1:(length(cifras_π)-length(cadena_N)) #Iteramos sobre las cifras de π
            if cadena_N[1] == cifras_π[i] #Vemos si el primer digito de N conincide con una cifra de π
                if prod(cadena_N[1+j] == cifras_π[i+j] for j ∈ 1:(length(cadena_N)-1)) #Si el primer digíto del número coincide...
                    return "El número se encuentra en $(i)"
                    break
                end   
            end
        end
        println("Este número no se encuentra en las primeras 6,020,601 cifras de π")
    end
end    

número_en_π (generic function with 1 method)

[10] **(fácil)** Calcula $\pi$ usando 3 métodos (haciendo las funciones correspondientes):

- Midiendo el área de un polígono regular de $n$ lados de radio 1. 
- Midiendo el perímetro de un polígono regular de $n$ lados de radio 1/2. 
- Calculando 2 veces el área bajo la curva de $ f(x) = \sqrt{1-x^2}$ entre -1 y 1, para $n = n$ (aquí la segunda $n$ en la igualdad se refiere al valor que asignan a $n$ el key argument de la función en 15). 

¿Qué método lo aproxima mejor al crecer $n$?

In [26]:
function areaPoligonor1(n::Int)
    1//2*n*sin(2π/n)
end

areaPoligonor1 (generic function with 1 method)

In [27]:
areaPoligonor1(1000)

3.1415719827794755

In [28]:
function perimetroPoligonorMedio(n::Int)
    n*sin(2π/n)/2*sin(π*(1//2-1/n))
end

perimetroPoligonorMedio (generic function with 1 method)

In [29]:
perimetroPoligonorMedio(1000)

3.1415564797558924

In [30]:
2 * area_de_funciones(-1.0, 1, 1000, x -> sqrt(1-x^2))

3.1414874770021437

[11] **(fácil)** Haz una función que dado un ángulo y rapidez inicial, calcule la distancia (y tiempo) que recorre (tarda) una partícula que se tira con tiro parabólico hasta que llegue a la misma altura que la que salió. 

In [31]:
"""
Esta función calcula el alcance máximo y el tiempo de vuelo de un tiro parabólico
"""
function tiroParabolico(v_0::Real, θ::Real, g = 9.81)
    t = 2 * v_0 * sin(θ) / g
    d = v_0 ^2 * sin(2 * θ) / g
    return d, t
end

tiroParabolico

In [32]:
tiroParabolico(10,0.78)

(10.193085833129116, 1.433801058512559)

## Objetos

[12] **(fácil)** Haz un objeto Segmento y otro Polígono. El objeto Segmento debe tener 3 entradas que corresponden al inicio y al final del segmento y a su longitud. El objeto Polígono debe tener 4 entradas, un arreglo de vértices, un arreglo de segmentos, el perímetro y el área del polígono. 

In [33]:
abstract type Figura end

In [34]:
mutable struct Segmento <: Figura
    inicio::Array{Float64}
    final::Array{Float64}
    longitud::Real
end

In [35]:
mutable struct Poligono <: Figura
    vertices::Array{Array{Float64, 1}, 1}
    segmentos::Array{Float64, 1}
    perimetro::Real
    area::Real
end

[13] **(fácil)** Haz un par de funciones que se llamen Segmento y Polígono, que tomen como argumentos para Segmento, el vértice inicial y el vértice final de un segmento, para la función Polígono, que tome como argumentos un arreglo de vértices. Estas funciones deben arrojar los objetos Segmento y Polígono respectivamente. 

In [36]:
using LinearAlgebra

In [37]:
function Segmento(a::Array{Float64}, b::Array{Float64})
    l = norm(a-b)
    return Segmento(a,b,l)
end

Segmento

In [38]:
Segmento([3.0,4.0],[8.0,5.0])

Segmento([3.0, 4.0], [8.0, 5.0], 5.0990195135927845)

In [39]:
using LinearAlgebra
function Poligono(v::Array{Array{Float64,1},1})
    numlados = length(v)
    segmentos = [Segmento(v[i], v[i+1]).longitud for i ∈ 1:(numlados - 1)]
    push!(segmentos, Segmento(v[numlados], v[1]).longitud)
    perimetro = sum([lado for lado ∈ segmentos])
    return Poligono(v, segmentos, perimetro, area(v))
end

Poligono

In [40]:
Poligono([[0.0,0.0],[1.0,0.0],[1.0,1.0],[0.0,1.0]])

Poligono([[0.0, 0.0], [1.0, 0.0], [1.0, 1.0], [0.0, 1.0]], [1.0, 1.0, 1.0, 1.0], 4.0, 1.0)

[14] **(fácil)** Agrega los métodos *(a::Number, s::Segmento), *(s::Segmento, a::Number) y *(a::Number, p::Polígono), *(p::Polígono, a::Number), de tal forma que se produzca un segmento y un polígono respectivamente, con el mismo centro, pero con una longitud o perímetro multiplicados por a. 

In [41]:
import Base.*
function *(a::Number, f::Figura)
    if f isa Segmento
        f.longitud = a * f.longitud
        f.final = a * f.final
        return Segmento(s.inicio, s.final, s.longitud)
    elseif f isa Poligono
        vertices = [a * v for v ∈ f.vertices]
        return Poligono(vertices)
    else
        return -1
    end
end

* (generic function with 329 methods)

In [42]:
function *(f::Figura, a::Number)
    return *(a::Number, f::Figura)
end

* (generic function with 330 methods)

In [43]:
*(2,Segmento([1.0,2.0],[5.0,3.0]))

LoadError: UndefVarError: s not defined

In [44]:
*(2,Poligono([[0.0,0.0],[1.0,0.0],[0.0,1.0],[1.0,1.0]]))

Poligono([[0.0, 0.0], [2.0, 0.0], [0.0, 2.0], [2.0, 2.0]], [2.0, 2.8284271247461903, 2.0, 2.8284271247461903], 9.65685424949238, 4.0)

[15] **(fácil)** Agrega los métodos +(s1::Segmento, s2::Segmento), +(s1::Segmento, p1::Polígono) y +(p1::Polígono, s1::Segmento), de tal forma que el resultado de sumar ambos objetos sea un polígono. En el caso de sumar 2 segmentos, el polígono resultante debe ser el que comience en el primer vértice de s1, siga en el segundo vértice, continue al primer vértice de s2, luego pase al segundo vértice de s2. Similar con los casos de sumar segmento y polígono.

Nota: No es necesario, pero es mejor si tus métodos consideren el caso donde el primer vértice del segundo objeto coincida con el último vértice del primer objeto y en ese caso no repita el mismo vértice en el polígono final. Por ejemplo si s1 = Segmento([0,0], [1,1]) y s2 = Segmento([1,1], [2,1]), s1+s2 = Polígono([[0,0], [1,1], [2,1]]) y no igual a Polígono([[0,0], [1,1], [1,1], [2,1]]).  

In [45]:
import Base.+
function +(f::Figura...)
    vertices::Array{Array{Float64, 1}, 1} = [] 
    for  figura ∈ f 
        if figura isa  Segmento 
           vertices = vcat(vertices,[f.inicio, f.final])  
        elseif f isa Poligono 
           vertices = vcat(vertices, f.vertices) 
        else
           println("No es una Figura")
           return - 1
        end
     end   
     return Polígono(vertices)
end    

+ (generic function with 191 methods)

[16] **(talachudo)** Haz un objeto llamado Cuaternión que sea un número (vas a necesitar usar el objeto abstracto Number), que contenga la parte real, y las 3 partes imaginarias. Agrega a este objeto las operaciones de suma, resta, producto, cociente, conjugado, norma y exponencial (revisa cómo se operan los cuaternones aquí: https://en.wikipedia.org/wiki/Quaternion). 

Prueba que tu objeto hace lo que debe hacer un cuaternión con esas operaciones algebráicas básicas. 

Nota: Necesitarás cargar la paquetería de LinearAlgebra para la norma. 

In [46]:
mutable struct Cuaternion <: Number
    real::Real
    im::Array
end

In [47]:
function suma(a::Cuaternion, b::Cuaternion)
    return Cuaternion(a.real + b.real, .+(a.im, b.im))
end

suma (generic function with 1 method)

In [48]:
function resta(a::Cuaternion, b::Cuaternion)
    return Cuaternion(a.real - b.real, .-(a.im, b.im))
end

resta (generic function with 1 method)

In [49]:
function multescalar(c::Real, b::Cuaternion)
    return Cuaternion(c * b.real, c .* b.im)
end

multescalar (generic function with 1 method)

In [50]:
function conjugado(a::Cuaternion)
    return Cuaternion(a.real, - a.im)
end

conjugado (generic function with 1 method)

In [51]:
function producto(a::Cuaternion, b::Cuaternion)
    r = a.real * b.real - a.im ⋅ b.im
    i = a.real * b.im + a.im * b.real + a.im × b.im
    return Cuaternion(r, i)
end

producto (generic function with 1 method)

In [52]:
function norma(a::Cuaternion)
    return √(a.real ^ 2 + norm(a.im))
end

norma (generic function with 1 method)

In [53]:
using LinearAlgebra
function inverso(a::Cuaternion)
    r = a.real / norma(a)
    i = - a.im / norma(a)
    return Cuaternion(r,i)
end

inverso (generic function with 1 method)

In [54]:
using LinearAlgebra
function exponencial(a::Cuaternion)
    c = Cuaternion(0,[0,0,0])
    c.real = exp(a.real) * cos(norm(a.im))
    c.im = (exp(a.real) * sin(norm(a.im)) / norm(a.im)) * a.im
    return c
end

exponencial (generic function with 1 method)

In [55]:
a = Cuaternion(5,[1,2,3])
b = Cuaternion(4,[3,2,5])
c = 5.4
println(suma(a,b))
println(resta(a,b))
println(multescalar(c,a))
println(conjugado(a))
println(producto(a,b))
println(norma(a))
println(inverso(a))
println(exponencial(a))

Cuaternion(9, [4, 4, 8])
Cuaternion(1, [-2, 0, -2])
Cuaternion(27.0, [5.4, 10.8, 16.200000000000003])
Cuaternion(5, [-1, -2, -3])
Cuaternion(-2, [23, 22, 33])
5.361124638242795
Cuaternion(0.9326401338131993, [-0.18652802676263985, -0.3730560535252797, -0.5595840802879196])
Cuaternion(-122.48524100698262, [-22.398710948668615, -44.79742189733723, -67.19613284600584])


[17] **(dificultad media)** Un problema típico en física computacional es saber si una partícula se encuentra "dentro" de algo o "fuera" de ese algo. Para polígonos una forma de resolver esto es "lanzando semi-rayos" desde la partícula hacia el exterior. Si el semi-rayo cruza un número impar de aristas, entonces se encuentra dentro del polígono. Si cruza un número par se encuentra fuera. Haz una función que dado un polígono y un punto, diga si el punto se encuentra dentro o fuera del polígono. 

In [56]:
using LinearAlgebra
mutable struct segmen
    inicio::Vector{Float64}
    final::Vector{Float64}
    longitud::Float64   
    segmen(x,y)=new(x,y,norm(y-x))
end
mutable struct poli
    vertices::Array{Array{Float64,1},1}
    segm::Array{segmen}
    perimetro
    area
    function seg(x)
        return [(segmen(x[i],x[i+1])) for i in 1:(length(x)-1)] ∪ [segmen(x[length(x)],x[1])]
    end     
     poli(x)=new(x,seg(x),sum([(seg(x)[i].longitud) for i in 1:length(seg(x))]),area(x))
end

In [57]:
function particula_poligono(a::poli,p1::Vector{Float64})
    
    function cruza(s1::segmen,s2::segmen)       
        if (([s1.final[1]-s1.inicio[1],s1.final[2]-s1.inicio[2],0]×[s2.final[1]-s1.inicio[1],s2.final[2]-s1.inicio[2],0])[3] > 0) ⊻ (([s1.final[1]-s1.inicio[1],s1.final[2]-s1.inicio[2],0]×[s2.inicio[1]-s1.inicio[1],s2.inicio[2]-s1.inicio[2],0])[3] > 0)
            if (([s2.final[1]-s2.inicio[1],s2.final[2]-s2.inicio[2],0]×[s1.final[1]-s2.inicio[1],s1.final[2]-s2.inicio[2],0])[3] > 0) ⊻ (([s2.final[1]-s2.inicio[1],s2.final[2]-s2.inicio[2],0]×[s1.inicio[1]-s2.inicio[1],s1.inicio[2]-s2.inicio[2],0])[3] > 0)
                return 1
            else
                return 0
            end
        else
            return 0
        end
     end   
    function dir()        
        d=[rand()*rand([-1,1]),rand()*rand([-1,1])] #Tomamos una direccion aleatoria
        d=d/norm(d)
        return d
    end  
      p2=p1+2*maximum([norm(p1-a.vertices[i]) for i ∈ 1:length(a.vertices)])*dir()
     rayo=segmen(p1,p2)                       #Creamos el semi-rayo
      prueba=sum([cruza(rayo,a.segm[i]) for i ∈ 1:length(a.segm)])    
    if mod(prueba,2) == 0
        return "Afuera"
    else
        return "Adentro"
    end
end 
 x=[[-1.,-1.],[1.,-1.],[0.,1.]]
 triangulo=poli(x)
 particula_poligono(triangulo,[0.,2.])

"Afuera"

[18] **(dificultad media)** Modifica la función del problema 11, para que en vez de calcular cuándo llega a la misma altura, calcule cuándo llega (intersecta) una linea poligonal dada (un polígono, que puede contener dos segmentos infinitos). 

[19] **(difícil)** Haz el equivalente al problema 17, pero en 3D. Asegúrate que tu función hace lo que debe hacer (es decir, pruébala con ejemplos de poliedros adecuados).

Nota: Quizá la parte más difícil en este ejercicio es asegurarse de que la función calcula correctamente lo que se quiere. 