# Integrantes
- Alarcón Rodríguez Luis Guillermo
- Chávez Salgado Carlos Daniel
- Rodríguez Salas Carlos Oswaldo

# Tarea 1

Antes de comenzar con los problemas, quiero aclarar que esta primera tarea será sustancialmente más fácil que el resto para que no sea un inicio de golpe. Aún así es muy recomendable que hagan la tarea en equipos. 

La **fecha de entrega** es el día **30 de septiembre** y la hora máxima de entrega es a las **3pm**. Las tareas que se entreguen después de esa hora (google lo marca como con retraso), no las calificaré, así que será un 0 en la tarea. Tomen sus precauciones para que no les pase eso (tienen semana y media para una tarea fácil. Es mejor que la entreguen un par de días antes por lo menos). 

También quiero aclarar que no se pueden usar cosas que no se hayan visto en la primera tanda de videos a menos que el problema lo diga explícitamente. 

Por último, esta tarea la califico sobre 18. Si resuelves más de 18 ejercicios, no serán contados (aunque impresiona). 

## Notebooks 
**(todos los problemas de esta sección son fáciles)**

[1] En la siguiente celda escribe el teorema de Stokes (en Markdown) comenzando por el título del teorema en cursiva la pablabra "Stokes", el enunciado (con los símbolos matemáticos correspondientes). Pon una referencia a wikipedia del teorema (con un link que funcione). 

# Teorema de *Stokes*
Sea $\Sigma$ una superficie suave orientada en $\mathbb{R}^3$ con frontera $\partial{}\Sigma$. Si un campo vectorial $\bf{F}$ $= (P(x,y,z),Q(x,y,z),R(x,y,z))$ está definidio y tiene derivadas parciales continuas en una región abierta que contiene a $\Sigma$ entonces:

$\oint_{\partial{}\Sigma}\textbf{F}\cdot{d\textbf{r}}=\iint_{\Sigma}(\nabla{}\times{\textbf{F}})\cdot{d\textbf{S}}$ 

Este teorema fue encontrado en el siguiente enlace de [Wikipedia](https://es.wikipedia.org/wiki/Teorema_de_Stokes)

[2] En la siguiente celda, el código está en un formato incorrecto. Cambia las palabras que corresponden a símbolos (como letras griegas y operadores) por símbolos, quita los comentarios donde se tengan que quitar, vuelve comentario lo que sea texto explicativo, tabula donde está marcado que se tenga que tabular y quita el tabulado donde esté indicado. 

Nota: Este ejercicio tiene como propósito que uses los trucos para comentar y descomentar rápido, tabular rápido, cambiar en varios lugares texto, etc. Por supuesto, no es algo que podré ver que hayas hecho de la forma rápida, pero trata de hacerlo como práctica, te ayudará en el futuro. 

In [27]:
# vuelve esta celda una célda de código. Por ahora está en Raw. 

∫(f, a, b, δ = (b-a)/100) = ∑(f(a:δ:b))*δ   #cambiar integral por su símbolo y delta por su símbolo 
begin   #quitar 3 tabulados  
    δ = 0.01 #Cambiar deltat por símbolo y quitar 2 tabulados
    θ = rand()*2*π   #quitar 2 tambulados y cambiar las letras griegas por sus símbolos
    v = [cos(θ), sin(θ)] #quitar 2 tabulados y cambiar a símbolo de theta
    x = rand(2) #quitar 2 tabulados
    @show x # escribe aquí @show x con el tabulado correcto
    x = x+v*δ  #cambiar deltat por símbolo y quitar 2 tabulados
    @show x # escribe aquí @show x con el tabulado correcto
end #quitar 3 tabulados
for i ∈ 1:10  #Cambiar in por símbolo y comentar
    δ = 0.01 #Cambiar deltat por símbolo y comentar
    θ = rand()*2*π   #cambiar las letras griegas por sus símbolos y comentar
    v = [cos(θ), sin(θ)]  #cambiar a símbolo de theta y comentar
    x = rand(2) #quitar 2 tabulados
    @show x # escribe aquí @show x con el tabulado correcto
    x = x+v*δ  #cambiar deltat por símbolo y comentar
    @show x # escribe aquí @show x con el tabulado correcto
end #comentar

for i ∈ 1:10  #Cambiar in por símbolo y qutar comentario
    δ = 1e-5 #Cambiar deltat por símbolo y qutar comentario
    ϕ = rand()*π   #cambiar las letras griegas por sus símbolos y qutar comentario
    v = 2.3*[sin(ϕ), cos(ϕ), rand()]  #cambiar a símbolo de theta y qutar comentario
    x = rand(3) #qutar comentario
    @show x # escribe aquí @show x con el tabulado correcto
    x = x+v*δ + 4.9*[0,0,1]*δ^2 #cambiar deltat por símbolo y qutar comentario
    @show x # escribe aquí @show x con el tabulado correcto
end #qutar comentario   

x = [0.5441795569233694, 0.4271512471228702]
x = [0.5363776071569011, 0.4334066112083177]
x = [0.8643527435646443, 0.6038675407049783]
x = [0.8672818064977192, 0.5943061291808315]
x = [0.7175157083849482, 0.11985944954013372]
x = [0.7217108868864865, 0.11078197867318898]
x = [0.6064950174649686, 0.7045002941767511]
x = [0.6078216048559163, 0.6945886764533833]
x = [0.2766901319254931, 0.5198454393225451]
x = [0.2699889483273886, 0.5124228967403502]
x = [0.848783661569666, 0.8875819453940546]
x = [0.8573129112776019, 0.8928022805767488]
x = [0.5692454374516731, 0.5083299334007458]
x = [0.5657290571392195, 0.49896857294949787]
x = [0.6930257653223042, 0.8596336299509562]
x = [0.6901589637901604, 0.8500533664381242]
x = [0.29401876142583583, 0.3719186993147716]
x = [0.2845857396494231, 0.3752380516862024]
x = [0.943549091521865, 0.7689513183468284]
x = [0.9379422877239939, 0.7772316414789397]
x = [0.7284349137752988, 0.013640316666891472]
x = [0.7250629414177644, 0.023054656920994447]
x = 

[3] Utiliza la tecla Tab para completar lo que se pide en la siguiente celda. 

In [97]:
superficie_de_un_círculo(r) = 2π * r^2
# utilizando esta función para calcular la 
# superficie de un cilindro de radio 1 y altura 1.2, el volumen de un cilindro de imaginario y altura imaginaria 
#(la que quieras) y finalmente para calcular el volumne de una hiperesfera de dimensión 20 y radio 1. 
# Usa Tab para completar el nombre de la función superficie_de_un_círculo. 
superficie_cilindro(r,h) = 2 * superficie_de_un_círculo(r) + h * 2 * π * r
println(superficie_cilindro(1,1.2))
volumen_cilindro_im(r,h) = superficie_de_un_círculo(r)*h
println(volumen_cilindro_im(1+4*im,3*im))
volumen_hiperesfera(r,n) = superficie_de_un_círculo(r)^2 / factorial(n)
println(volumen_hiperesfera(1,20))

20.106192982974676
-150.79644737231007 - 282.74333882308133im
1.6226883561966758e-17


## Operaciones básicas y notación compacta

En esta sección usarás Julia como una calculadora sofisticada: 

[4] **(dificultad media)** La regla de años bisiestos es: Si un año es múltiplo de 4, entonces tiene 366 días, excepto si es múltiplo de 100, excepto si es múltiplo de 400. Por ejemplo, el año 2020 fue bisiesto por ser múltiplo de 4, el año 1900 también es multiplo de 4, pero no fue bisiesto por ser múltiplo de 100, en cambio el año 2000 sí fue bisiesto a pesar de ser múltiplo de 100, pues es también múltiplo de 400. En la historia, el día de la semana en que ocurre un evento puede ser importante (por ejemplo, porque era día de misa, de descanso, se hacía un tipo de trabajo, etc...).
Usando la función mod(x, n) calcula qué día de la semana fue: 

(i) El 15 de septiembre de 1810

(ii) El 24 de diciembre del año -1 (según nuestro calendario)

(iii) 20 de nomviembre de 1910

(iv) El día que naciste (o si prefieres, de algún personaje histórico que admires). 

In [21]:
# i
#Enúmeramos los meses del 3 a 14 para asegurar que los días
#bisiestos se encuentren al final del año
año=1810
mes = 9
día = 15
a=floor((14-mes)/12) #Se calcula el siglo 
y=año-a
m=mes+(12*a)-2
println(mod(día+y+floor(y/4)-floor(y/100)+floor(y/400)+floor((31*m)/12),7))
println("El día fue sábado")

6.0
El día fue sábado


In [22]:
# ii
año= -1
mes = 12
día = 24
a=floor((14-mes)/12) #Se calcula el siglo 
y=año-a
m=mes+(12*a)-2
println(mod(día+y+floor(y/4)-floor(y/100)+floor(y/400)+floor((31*m)/12),7))
println("El día fue viernes")

5.0
El día fue viernes


In [23]:
# iii
año=1910
mes = 11
día = 20
a=floor((14-mes)/12) #Se calcula el siglo 
y=año-a
m=mes+(12*a)-2
println(mod(día+y+floor(y/4)-floor(y/100)+floor(y/400)+floor((31*m)/12),7))
println("El día fue domingo")

0.0
El día fue domingo


In [24]:
# iv
año=1999
mes = 5
día = 18
a=floor((14-mes)/12) #Se calcula el siglo 
y=año-a
m=mes+(12*a)-2
println(mod(día+y+floor(y/4)-floor(y/100)+floor(y/400)+floor((31*m)/12),7))
println("El día fue martes")

2.0
El día fue martes


[5] **(fácil)** Calcula el ángulo entre el eje x y los siguientes vectores usando la función atan(x,y)

(i) $\vec{x} = (2.31, -\sqrt{5})$

(ii) $\vec{x} = (-\pi, -1)$

In [3]:
println(atan(-√5,2.31))
println(atan(1,π))

-0.7691367467081696
0.30816907111598496


[6] **(fácil)** Con las siguientes variables haz un arreglo que contenga los tipos de variables usando la función typeof

In [6]:
x1 = 1.2344444444444442211111111111111111111112434433
x2 = "1.2344444444444442211111111111111111111112434433"
x3 = [1 2 3; 4 5 6]
x4 = length(x2)
x5 = (1+ im)*x1 +x4
x6 = 1/Inf
x7 = 1//2
x8 = 0/0
x9 = missing
x10 = size(x3)
x11 = atan(x10...);
x = (x1,x2,x3,x4,x5,x6,x7,x8,x9,x10,x11)
println(typeof(x))

Tuple{Float64, String, Matrix{Int64}, Int64, ComplexF64, Float64, Rational{Int64}, Float64, Missing, Tuple{Int64, Int64}, Float64}


[7] **(dificultad media)** Escribe una serie de operadores booleanos aplicados sobre una variable x, de tal forma que si x es un número (entero, real, racional o complejo) arroje true, en otro caso arroje false (eso incluye vectores). 

Tu respuesta pruébala con las variables del ejercicio anterior

In [13]:
z = typeof.(x)
println(z)
y = length(x)
[typeof(x[i]) .== z for i ∈ 1:y]

(Float64, String, Matrix{Int64}, Int64, ComplexF64, Float64, Rational{Int64}, Float64, Missing, Tuple{Int64, Int64}, Float64)


11-element Vector{NTuple{11, Bool}}:
 (1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1)
 (0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0)
 (0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0)
 (0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0)
 (0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0)
 (1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1)
 (0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0)
 (1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1)
 (0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0)
 (0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0)
 (1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1)

[8] **(dificultad media)** Con notación compacta escribe un vector que tenga como entradas impares los números del 1 al 100 en forma de cadena y las entradas impares que sean "+" (es decir, algo de la forma ["1", "+", "2", ..., "+", "100"]). Usando ese arreglo y la concatenación de cadenas (usando la funcion prod) imprime (usa la función println) la suma y la evaluación de esa suma (no la evalues tú, que se evalue como parte de la cadena final. Es decir, el resultado final debe imprimir algo del tipo (en este ejemplo sólo sumo hasta 5): 

1+2+3+4+5 = 15

In [25]:
a = ["$i" for i ∈ 1:100]                                 # Creamos un vector donde las entradas son strings del 1 al 100 (i.e., ["1","2","3",...])
f(x) = insert!(a, x  ,"+")                               # Una función donde el argumento es el lugar de _a_ donde se le va a insertar "+"  
f.(i for i ∈ 2:2:199)                                    # Aplicamos la función para cada elemento del arreglo (nota: por cada vez que se aplica la f, _a_ se actualiza)
println(prod(a) * " = $(sum(1:100))")                    # Imprimimos (la concatenación de la _a_ actualizada y le pegamos el resultado de la suma)

1+2+3+4+5+6+7+8+9+10+11+12+13+14+15+16+17+18+19+20+21+22+23+24+25+26+27+28+29+30+31+32+33+34+35+36+37+38+39+40+41+42+43+44+45+46+47+48+49+50+51+52+53+54+55+56+57+58+59+60+61+62+63+64+65+66+67+68+69+70+71+72+73+74+75+76+77+78+79+80+81+82+83+84+85+86+87+88+89+90+91+92+93+94+95+96+97+98+99+100 = 5050


[9] **(fácil)** El siguiente texto (sin ninguna modificación) tiene un mensaje oculto:


"Éste texto no lo entiende cualquera, solamente dando el arreglo fijado vereís el mensaje oculto aquí: 
Si crees que con mágia puedes encontrar el mensaje escondido no estarás mal. Saber programar no es saber mágia
(sea lo que sea que eso signifique), pero para muchos lo que lograrán será casi como mágia blanca (de esa que
sólo se usa para el bien). Puedes por ejemplo diagnosticar una enfermedad sin conocer de medicina o predecir 
el clima, incluso puedes controlar aparatos a kilómetros de distancia."

Para desifrarlo necesitas una llave (el arreglo fijado), que es el siguiente arreglo (los elementos de la cadena de caracteres)

[5, 16, 18, 28, 29, 35, 39,40, 48, 49, 55, 57, 66, 77, 79, 93, 99, 105, 110, 121, 124, 131, 132, 143,145, 161, 165, 167, 169, 182, 183, 185, 189, 206, 207, 211, 226, 267, 268, 288, 292, 297, 315, 338, 358, 382, 388, 414]

Di cual es el mensaje oculto!

**Nota:** Los acentos en este texto son un poco problemáticos, así que debes cuidar no modificar el texto NADA para que puedas usar la llave. También es importante que consideres los cambios de línea. 

In [27]:
p = [5, 16, 18, 28, 29, 35, 39,40, 48, 49, 55, 57, 66, 77, 79, 93, 99, 105, 110, 121, 124, 131, 132, 143,145, 161, 165, 167, 169, 182, 183, 185, 189, 206, 207, 211, 226, 267, 268, 288, 292, 297, 315, 338, 358, 382, 388, 414]
o=length(p)
t=["Éste texto no lo entiende cualquera, solamente dando el arreglo fijado vereís el mensaje oculto aquí: 
Si crees que con mágia puedes encontrar el mensaje escondido no estarás mal. Saber programar no es saber mágia
(sea lo que sea que eso signifique), pero para muchos lo que lograrán será casi como mágia blanca (de esa que
sólo se usa para el bien). Puedes por ejemplo diagnosticar una enfermedad sin conocer de medicina o predecir 
el clima, incluso puedes controlar aparatos a kilómetros de distancia."[p[i]] for i ∈ 1:o ]
prod(t[i] for i ∈ 1:length(t))

"el curso de físca computacional es el más bonito"

[10] **(fácil)** El siguiente arreglo son las mediciones de la radiación dentro de un material a diferentes profundidades (cada medición es un mm mas profundo). Teóricamente la radiación debería decaer como $e^{-\lambda x}$, con $x$ la profundidad de la medición. 
Encuentra el valor de $\lambda$. Para esto calcula el logaritmo de la medición y dividelo por $x$ (omítelo, el segundo divídelo entre 1, el segundo entre 2, etc... ) y finalmente obten el promedio de eso. Además calcula el error (es decir, el valor absoluto de la diferencia entre la medición y el valor teórico).  

In [29]:
mediciones = [1.0, 0.999000499833375, 0.9980019986673331, 0.997004495503373, 0.9960079893439915, 0.9950124791926823, 0.9940179640539353, 0.9930244429332351, 0.9920319148370607, 0.9910403787728836, 0.9900498337491681, 0.9890602787753687, 0.9880717128619305, 0.9870841350202876, 0.9860975442628619, 0.9851119396030626, 0.9841273200552851, 0.9831436846349096, 0.9821610323583008, 0.981179362242806, 0.9801986733067553, 0.9792189645694596, 0.97824023505121, 0.9772624837732771, 0.9762857097579093, 0.9753099120283326, 0.9743350896087494, 0.9733612415243368, 0.9723883668012469, 0.9714164644666048, 0.9704455335485082, 0.9694755730760259, 0.9685065820791976, 0.967538559589032, 0.9665715046375066, 0.9656054162575665, 0.9646402934831231, 0.9636761353490535, 0.9627129408911995, 0.9617507091463667, 0.9607894391523232, 0.9598291299477989, 0.9588697805724845, 0.9579113900670306, 0.9569539574730467, 0.9559974818331, 0.9550419621907147, 0.9540873975903711, 0.9531337870775047, 0.9521811296985049, 0.951229424500714, 0.950278670532427, 0.9493288668428895, 0.9483800124822982, 0.9474321065017983, 0.9464851479534838, 0.9455391358903963, 0.9445940693665233, 0.9436499474367985, 0.9427067691570997, 0.9417645335842487, 0.9408232397760097, 0.9398828867910889, 0.9389434736891332, 0.9380049995307295, 0.9370674633774034, 0.9361308642916188, 0.9351952013367766, 0.9342604735772135, 0.933326680078202, 0.9323938199059483, 0.9314618921275921, 0.9305308958112057, 0.9296008300257927, 0.9286716938412872, 0.9277434863285529, 0.9268162065593822, 0.9258898536064953, 0.9249644265435393, 0.9240399244450868, 0.9231163463866358, 0.922193691444608, 0.9212719586963487, 0.9203511472201247, 0.9194312560951247, 0.9185122844014574, 0.9175942312201509, 0.9166770956331523, 0.9157608767233256, 0.914845573574452, 0.9139311852712282, 0.9130177108992658, 0.9121051495450904, 0.9111935002961405, 0.910282762240767, 0.9093729344682314, 0.9084640160687062, 0.9075560061332727, 0.9066489037539209, 0.9057427080235485, 0.9048374180359595, 0.9039330328858641, 0.9030295516688768, 0.9021269734815165, 0.9012252974212047, 0.9003245225862656, 0.899424648075924, 0.8985256729903055, 0.8976275964304349, 0.8967304174982355, 0.8958341352965282, 0.894938748929031, 0.8940442575003572, 0.8931506601160155, 0.8922579558824083, 0.8913661439068313, 0.8904752232974726, 0.8895851931634113, 0.8886960526146174, 0.8878078007619501, 0.8869204367171575, 0.8860339595928756, 0.8851483685026271, 0.8842636625608209, 0.8833798408827509, 0.8824969025845955, 0.8816148467834161, 0.880733672597157, 0.8798533791446438, 0.8789739655455832, 0.8780954309205613, 0.8772177743910435, 0.8763409950793732, 0.8754650921087711, 0.874590064603334, 0.8737159116880344, 0.8728426324887193, 0.8719702261321094, 0.8710986917457983, 0.8702280284582515, 0.8693582353988059, 0.8684893116976679, 0.867621256485914, 0.8667540688954889, 0.865887748059205, 0.8650222931107413, 0.8641577031846428, 0.8632939774163194, 0.8624311149420455, 0.8615691148989583, 0.8607079764250578, 0.8598476986592055, 0.8589882807411234, 0.8581297218113938, 0.8572720210114574, 0.8564151774836135, 0.8555591903710185, 0.8547040588176851, 0.8538497819684817, 0.8529963589691315, 0.8521437889662113, 0.8512920711071511, 0.850441204540233, 0.8495911884145902, 0.8487420218802068, 0.8478937040879159, 0.8470462341893996, 0.8461996113371882, 0.8453538346846587, 0.8445089033860343, 0.8436648165963837, 0.8428215734716199, 0.8419791731684999, 0.8411376148446232, 0.8402968976584314, 0.8394570207692074, 0.838617983337074, 0.8377797845229938, 0.8369424234887681, 0.8361058993970355, 0.835270211411272, 0.8344353586957896, 0.8336013404157353, 0.832768155737091, 0.8319358038266718, 0.8311042838521256, 0.8302735949819326, 0.8294437363854039, 0.8286147072326806, 0.8277865066947336, 0.8269591339433623, 0.8261325881511938, 0.8253068684916823, 0.8244819741391082, 0.8236579042685769, 0.8228346580560184, 0.8220122346781865, 0.821190633312658, 0.8203698531378311, 0.8195498933329256, 0.8187307530779818, 0.8179124315538594, 0.8170949279422366, 0.8162782414256099, 0.8154623711872927, 0.8146473164114145, 0.8138330762829207, 0.813019649987571, 0.812207036711939, 0.8113952356434114, 0.8105842459701871, 0.8097740668812763, 0.8089646975664998, 0.8081561372164884, 0.8073483850226815, 0.8065414401773269, 0.8057353018734796, 0.8049299693050015, 0.8041254416665596, 0.8033217181536265, 0.8025187979624785, 0.8017166802901953, 0.8009153643346592, 0.8001148492945541, 0.7993151343693651, 0.7985162187593771, 0.7977181016656743, 0.7969207822901396, 0.7961242598354538, 0.7953285335050939, 0.794533602503334, 0.7937394660352427, 0.7929461233066837, 0.792153573524314, 0.7913618158955839, 0.7905708496287356, 0.7897806739328027, 0.7889912880176096, 0.7882026910937704, 0.7874148823726879, 0.7866278610665535, 0.7858416263883455, 0.7850561775518295, 0.7842715137715565, 0.7834876342628625, 0.7827045382418681, 0.7819222249254772, 0.7811406935313765, 0.7803599432780343, 0.7795799733847004, 0.7788007830714049, 0.7780223715589573, 0.7772447380689461, 0.7764678818237378, 0.775691802046476, 0.774916497961081, 0.7741419687922484, 0.7733682137654491, 0.772595232106928, 0.7718230230437034, 0.7710515858035663, 0.7702809196150792, 0.7695110237075758, 0.7687418973111603, 0.7679735396567061, 0.7672059499758557, 0.7664391275010192, 0.7656730714653739, 0.764907781102864, 0.764143255648199, 0.7633794943368531, 0.7626164964050653, 0.7618542610898376, 0.7610927876289343, 0.7603320752608821, 0.7595721232249685, 0.7588129307612413, 0.7580544971105083, 0.7572968215143355, 0.7565399032150474, 0.7557837414557255, 0.755028335480208, 0.754273684533089, 0.7535197878597172, 0.7527666447061963, 0.7520142543193826, 0.751262615946886, 0.750511728837068, 0.7497615922390413, 0.7490122054026693, 0.7482635675785653, 0.747515678018091, 0.7467685359733571, 0.7460221406972215, 0.7452764914432887, 0.7445315874659094, 0.7437874280201796, 0.7430440123619398, 0.7423013397477743, 0.7415594094350105, 0.7408182206817179, 0.7400777727467076, 0.7393380648895319, 0.7385990963704826, 0.7378608664505911, 0.7371233743916278, 0.7363866194561001, 0.7356506009072533, 0.7349153180090687, 0.7341807700262634, 0.7334469562242892, 0.7327138758693325, 0.7319815282283126, 0.731249912568882, 0.7305190281594249, 0.7297888742690568, 0.7290594501676237, 0.7283307551257017, 0.7276027884145955, 0.7268755493063382, 0.7261490370736909, 0.7254232509901412, 0.7246981903299029, 0.7239738543679153, 0.7232502423798424, 0.7225273536420722, 0.7218051874317158, 0.721083743026607, 0.7203630197053014, 0.7196430167470754, 0.7189237334319262, 0.7182051690405703, 0.7174873228544433, 0.716770194155699, 0.7160537822272085, 0.7153380863525599, 0.7146231058160573, 0.71390883990272, 0.7131952878982822, 0.7124824490891918, 0.7117703227626097, 0.7110589082064097, 0.7103482047091773, 0.7096382115602087, 0.7089289280495107, 0.7082203534678, 0.7075124871065016, 0.7068053282577494, 0.7060988762143844, 0.7053931302699543, 0.7046880897187134, 0.703983753855621, 0.7032801219763409, 0.7025771933772416, 0.701874967355394, 0.7011734432085724, 0.7004726202352524, 0.699772497734611, 0.6990730750065257, 0.6983743513515736, 0.697676326071031, 0.6969789984668727, 0.696282367841771, 0.6955864334990951, 0.6948911947429106, 0.6941966508779789, 0.6935028012097558, 0.6928096450443917, 0.6921171816887304, 0.6914254104503085, 0.6907343306373547, 0.690043941558789, 0.6893542425242224, 0.6886652328439558, 0.6879769118289795, 0.6872892787909722, 0.686602333042301, 0.6859160738960202, 0.6852305006658703, 0.6845456126662782, 0.6838614092123558, 0.6831778896198997, 0.6824950532053901, 0.6818128992859905, 0.6811314271795471, 0.6804506362045877, 0.679770525680321, 0.6790910949266368, 0.678412343264104, 0.6777342700139711, 0.6770568744981647, 0.6763801560392891, 0.675704113960626, 0.6750287475861332, 0.6743540562404442, 0.6736800392488677, 0.6730066959373864, 0.6723340256326573, 0.6716620276620098, 0.6709907013534459, 0.6703200460356393, 0.6696500610379346, 0.6689807456903467, 0.6683120993235603, 0.6676441212689289, 0.6669768108584744, 0.6663101674248864, 0.6656441903015212, 0.6649788788224019, 0.6643142323222168, 0.6636502501363194, 0.6629869316007274, 0.6623242760521222, 0.6616622828278483, 0.6610009512659124, 0.6603402807049829, 0.659680270484389, 0.6590209199441207, 0.6583622284248272, 0.657704195267817, 0.6570468198150567, 0.6563901014091712, 0.6557340393934418, 0.6550786331118063, 0.6544238819088586, 0.6537697851298473, 0.6531163421206756, 0.6524635522279004, 0.651811414798732, 0.6511599291810325, 0.6505090947233165, 0.6498589107747496, 0.6492093766851474, 0.6485604918049761, 0.6479122554853506, 0.6472646670780347, 0.6466177259354396, 0.6459714314106245, 0.6453257828572946, 0.6446807796298013, 0.6440364210831414, 0.6433927065729562, 0.6427496354555312, 0.6421072070877952, 0.6414654208273198, 0.6408242760323187, 0.6401837720616471, 0.6395439082748009, 0.6389046840319162, 0.6382660986937688, 0.6376281516217733, 0.6369908421779825, 0.6363541697250871, 0.6357181336264143, 0.6350827332459281, 0.6344479679482282, 0.633813837098549, 0.6331803400627598, 0.6325474762073634, 0.6319152448994959, 0.631283645506926, 0.6306526773980542, 0.6300223399419123, 0.6293926325081629, 0.6287635544670984, 0.6281351051896408, 0.6275072840473407, 0.626880090412377, 0.6262535236575559, 0.6256275831563107, 0.6250022682827008, 0.6243775784114112, 0.623753512917752, 0.6231300711776578, 0.6225072525676867, 0.62188505646502, 0.6212634822474616, 0.6206425292934373, 0.6200221969819939, 0.6194024846927992, 0.6187833918061408, 0.6181649177029258, 0.61754706176468, 0.6169298233735474, 0.6163132019122897, 0.6156971967642851, 0.6150818073135287, 0.6144670329446308, 0.6138528730428171, 0.6132393269939275, 0.6126263941844161, 0.6120140740013499, 0.6114023658324087, 0.6107912690658842, 0.6101807830906798, 0.6095709072963093, 0.6089616410728969, 0.6083529838111763, 0.6077449349024902, 0.6071374937387897, 0.6065306597126334, 0.6059244322171875, 0.6053188106462242, 0.6047137943941221, 0.6041093828558647, 0.6035055754270405, 0.6029023715038421, 0.6022997704830654, 0.6016977717621094, 0.6010963747389753, 0.6004955788122659, 0.5998953833811855, 0.5992957878455384, 0.5986967916057292, 0.5980983940627613, 0.5975005946182375, 0.596903392674358, 0.596306787633921, 0.5957107789003212, 0.5951153658775501, 0.5945205479701944, 0.5939263245834361, 0.593332695123052, 0.5927396589954125, 0.5921472156074813, 0.5915553643668151, 0.5909641046815626, 0.5903734359604639, 0.5897833576128504, 0.5891938690486437, 0.5886049696783552, 0.5880166589130854, 0.5874289361645234, 0.5868418008449466, 0.5862552523672196, 0.5856692901447937, 0.5850839135917069, 0.5844991221225824, 0.5839149151526287, 0.5833312920976388, 0.5827482523739896, 0.5821657953986414, 0.5815839205891371, 0.5810026273636019, 0.5804219151407424, 0.5798417833398464, 0.579262231380782, 0.5786832586839974, 0.5781048646705196, 0.5775270487619547, 0.5769498103804866, 0.5763731489488771, 0.5757970638904645, 0.5752215546291638, 0.5746466205894657, 0.574072261196436, 0.5734984758757153, 0.5729252640535184, 0.5723526251566332, 0.5717805586124209, 0.5712090638488149, 0.5706381402943203, 0.5700677873780134, 0.5694980045295416, 0.5689287911791218, 0.5683601467575404, 0.5677920706961532, 0.5672245624268841, 0.5666576213822246, 0.5660912469952337, 0.5655254386995371, 0.5649601959293262, 0.5643955181193583, 0.5638314047049556, 0.5632678551220046, 0.5627048688069557, 0.5621424451968224, 0.5615805837291813, 0.5610192838421706, 0.5604585449744904, 0.559898366565402, 0.5593387480547268, 0.5587796888828463, 0.5582211884907012, 0.5576632463197913, 0.5571058618121739, 0.5565490344104649, 0.5559927635578367, 0.5554370486980182, 0.5548818892752949, 0.5543272847345071, 0.5537732345210501, 0.5532197380808739, 0.5526667948604818, 0.5521144043069306, 0.5515625658678298, 0.5510112789913407, 0.5504605431261766, 0.5499103577216016, 0.54936072222743, 0.5488116360940265, 0.5482630987723047, 0.5477151097137275, 0.5471676683703055, 0.5466207741945976, 0.5460744266397094, 0.5455286251592933, 0.544983369207548, 0.5444386582392171, 0.5438944917095899, 0.5433508690744998, 0.542807789790324, 0.5422652533139832, 0.541723259102941, 0.5411818066152029, 0.5406408953093166, 0.5401005246443706, 0.5395606940799943, 0.539021403076357, 0.5384826510941678, 0.5379444375946745, 0.5374067620396636, 0.5368696238914595, 0.5363330226129241, 0.535796957667456, 0.5352614285189903, 0.5347264346319975, 0.5341919754714841, 0.5336580505029906, 0.5331246591925921, 0.5325918010068972, 0.5320594754130477, 0.5315276818787179, 0.5309964198721143, 0.5304656888619749, 0.5299354883175685, 0.5294058177086945, 0.5288766765056825, 0.528348064179391, 0.5278199802012077, 0.5272924240430485, 0.5267653951773574, 0.5262388930771054, 0.5257129172157903, 0.5251874670674361, 0.5246625421065929, 0.5241381418083354, 0.5236142656482635, 0.5230909131025008, 0.5225680836476948, 0.522045776761016, 0.5215239919201575, 0.5210027286033344, 0.5204819862892832, 0.5199617644572618, 0.5194420625870482, 0.5189228801589404, 0.5184042166537559, 0.5178860715528314, 0.5173684443380216, 0.5168513344916992, 0.5163347414967544, 0.5158186648365941, 0.5153031039951417, 0.5147880584568362, 0.5142735277066319, 0.5137595112299983, 0.5132460085129188, 0.5127330190418905, 0.512220542303924, 0.5117085777865424, 0.5111971249777814, 0.5106861833661879, 0.5101757524408203, 0.5096658316912476, 0.5091564206075492, 0.5086475186803137, 0.5081391254006393, 0.5076312402601327, 0.5071238627509086, 0.5066169923655895, 0.5061106285973052, 0.5056047709396915, 0.5050994188868908, 0.5045945719335512, 0.5040902295748255, 0.5035863913063714, 0.5030830566243506, 0.5025802250254283, 0.502077896006773, 0.5015760690660555, 0.5010747437014489, 0.5005739194116277, 0.5000735956957676, 0.4995737720535449, 0.49907444798513595, 0.4985756229912165, 0.4980772965729616, 0.4975794682320448, 0.4970821374706377, 0.49658530379140947, 0.49608896669752645, 0.4955931256926514, 0.4950977802809434, 0.494602929967057, 0.4941085742561417, 0.4936147126538418, 0.49312134466629576, 0.49262846980013547, 0.492136087562486, 0.4916441974609651, 0.4911527990036827, 0.4906618916992401, 0.4901714750567302, 0.4896815485857362, 0.48919211179633154, 0.4887031641990795, 0.4882147053050323, 0.4877267346257312, 0.48723925167320525, 0.4867522559599717, 0.4862657469990346, 0.485779724303885, 0.4852941873885002, 0.48480913576734325, 0.48432456895536247, 0.483840486467991, 0.48335688782114633, 0.48287377253122976, 0.48239114011512596, 0.48190899009020244, 0.4814273219743092, 0.480946135285778, 0.48046542954342225, 0.479985204266536, 0.4795054589748941, 0.47902619318875106, 0.4785474064288412, 0.4780690982163776, 0.4775912680730521, 0.4771139155210344, 0.47663704008297203, 0.4761606412819894, 0.4756847186416878, 0.47520927168614446, 0.4747342999399124, 0.4742598029280199, 0.4737857801759698, 0.4733122312097393, 0.47283915555577954, 0.4723665527410147, 0.471894422292842, 0.4714227637391309, 0.4709515766082228, 0.47048086042893056, 0.47001061473053796, 0.46954083904279925, 0.4690715328959387, 0.46860269582065023, 0.4681343273480965, 0.46766642700990924, 0.4671989943381879, 0.46673202886549986, 0.46626553012487953, 0.46579949764982825, 0.4653339309743134, 0.46486882963276827, 0.46440419316009157, 0.4639400210916467, 0.4634763129632616, 0.46301306831122807, 0.4625502866723014, 0.4620879675837, 0.4616261105831047, 0.4611647152086584, 0.4607037809989658, 0.46024330749309256, 0.4597832942305652, 0.45932374075137034, 0.4588646465959545, 0.4584060113052235, 0.45794783442054204, 0.45749011548373314, 0.4570328540370779, 0.4565760496233147, 0.4561197017856392, 0.4556638100677035, 0.45520837401361586, 0.45475339316794017, 0.4542988670756955, 0.45384479528235583, 0.4533911773338492, 0.4529380127765577, 0.4524853011573167, 0.45203304202341466, 0.4515812349225922, 0.45112987940304233, 0.4506789750134095, 0.45022852130278923, 0.44977851782072775, 0.44932896411722156, 0.448879859742717, 0.4484312042481095, 0.44798299718474366, 0.44753523810441237, 0.4470879265593564, 0.44664106210226434, 0.44619464428627154, 0.4457486726649602, 0.4453031467923587, 0.4448580662229411, 0.4444134305116268, 0.44396923921378006, 0.4435254918852095, 0.44308218808216776, 0.4426393273613511, 0.44219690927989863, 0.4417549333953923, 0.44131339926585617, 0.4408723064497561, 0.44043165450599925, 0.43999144299393356, 0.43955167147334756, 0.43911233950446965, 0.4386734466479678, 0.4382349924649492, 0.4377969765169596, 0.437359398365983, 0.43692225757444114, 0.4364855537051933, 0.43604928632153556, 0.43561345498720044, 0.43517805926635666, 0.43474309872360845, 0.4343085729239951, 0.4338744814329909, 0.4334408238165043, 0.43300759964087765, 0.43257480847288665, 0.43214244987974026, 0.43171052342907973, 0.43127902868897855, 0.43084796522794205, 0.43041733261490667, 0.4299871304192398, 0.42955735821073915, 0.42912801555963254, 0.42869910203657724, 0.4282706172126597, 0.427842560659395, 0.4274149319487267, 0.4269877306530259, 0.4265609563450914, 0.4261346085981487, 0.4257086869858502, 0.42528319108227414, 0.42485812046192456, 0.4244334746997309, 0.4240092533710473, 0.4235854560516524, 0.4231620823177488, 0.42273913174596284, 0.42231660391334386, 0.4218944983973639, 0.42147281477591764, 0.4210515526273212, 0.42063071153031245, 0.4202102910640503, 0.41979029080811425, 0.41937071034250395, 0.418951549247639, 0.41853280710435814, 0.41811448349391933, 0.4176965779979988, 0.41727909019869114, 0.4168620196785084, 0.41644536602038007, 0.4160291288076525, 0.4156133076240884, 0.4151979020538666, 0.4147829116815814, 0.41436833609224244, 0.4139541748712741, 0.41354042760451515, 0.4131270938782182, 0.41271417327904963, 0.41230166539408875, 0.4118895698108276, 0.41147788611717057, 0.41106661390143395, 0.4106557527523455, 0.410245302259044, 0.40983526201107895, 0.40942563159841006, 0.4090164106114069, 0.40860759864084845, 0.4081991952779227, 0.4077912001142262, 0.4073836127417638, 0.40697643275294815, 0.4065696597405991, 0.4061632932979437, 0.40575733301861544, 0.405351778496654, 0.4049466293265049, 0.4045418851030188, 0.4041375454214515, 0.4037336098774634, 0.40333007806711874, 0.40292694958688574, 0.40252422403363597, 0.40212190100464373, 0.401719980097586, 0.4013184609105419, 0.4009173430419921, 0.4005166260908188, 0.40011630965630496, 0.3997163933381341, 0.3993168767363899, 0.39891775945155566, 0.39851904108451414, 0.39812072123654696, 0.39772279950933415, 0.397325275504954, 0.39692814882588245, 0.39653141907499284, 0.39613508585555535, 0.3957391487712367, 0.3953436074260998, 0.39494846142460327, 0.3945537103716011, 0.3941593538723422, 0.39376539153247, 0.3933718229580221, 0.39297864775542996, 0.39258586553151836, 0.39219347589350495, 0.39180147844900015, 0.3914098728060065, 0.3910186585729182, 0.3906278353585211, 0.39023740277199187, 0.38984736042289797, 0.38945770792119694, 0.3890684448772363, 0.388679570901753, 0.38829108560587294, 0.3879029886011109, 0.3875152794993697, 0.38712795791294036, 0.3867410234545012, 0.3863544757371177, 0.3859683143742421, 0.38558253897971306, 0.38519714916775516, 0.3848121445529785, 0.3844275247503785, 0.3840432893753352, 0.38365943804361335, 0.3832759703713615, 0.38289288597511206, 0.38251018447178037, 0.38212786547866506, 0.3817459286134471, 0.38136437349418956, 0.38098319973933725, 0.38060240696771647, 0.38022199479853436, 0.3798419628513787, 0.37946231074621756, 0.37908303810339883, 0.37870414454364976, 0.3783256296880768, 0.37794749315816506, 0.37756973457577797, 0.37719235356315695, 0.37681534974292086, 0.37643872273806595, 0.37606247217196515, 0.37568659766836787, 0.37531109885139957, 0.37493597534556133, 0.3745612267757298, 0.37418685276715613, 0.3738128529454665, 0.37343922693666093, 0.3730659743671134, 0.3726930948635714, 0.3723205880531552, 0.3719484535633582, 0.3715766910220457, 0.37120530005745517, 0.37083428029819565, 0.37046363137324734, 0.3700933529119613, 0.369723444544059, 0.369353905899632, 0.3689847366091418, 0.3686159363034188, 0.3682475046136629, 0.36787944117144233]

1001-element Vector{Float64}:
 1.0
 0.999000499833375
 0.9980019986673331
 0.997004495503373
 0.9960079893439915
 0.9950124791926823
 0.9940179640539353
 0.9930244429332351
 0.9920319148370607
 0.9910403787728836
 0.9900498337491681
 0.9890602787753687
 0.9880717128619305
 ⋮
 0.3719484535633582
 0.3715766910220457
 0.37120530005745517
 0.37083428029819565
 0.37046363137324734
 0.3700933529119613
 0.369723444544059
 0.369353905899632
 0.3689847366091418
 0.3686159363034188
 0.3682475046136629
 0.36787944117144233

In [30]:
log.(mediciones[i] for i ∈ 1:length(mediciones))

1001-element Vector{Float64}:
  0.0
 -0.0009999999999999697
 -0.001999999999999988
 -0.0029999999999999753
 -0.003999999999999988
 -0.004999999999999993
 -0.005999999999999988
 -0.0069999999999999975
 -0.007999999999999972
 -0.009000000000000017
 -0.009999999999999946
 -0.01099999999999997
 -0.012000000000000023
  ⋮
 -0.9889999999999999
 -0.99
 -0.9910000000000001
 -0.9920000000000001
 -0.9930000000000001
 -0.9939999999999999
 -0.995
 -0.996
 -0.9969999999999999
 -0.998
 -0.999
 -1.0

[11] **(fácil)** Ordena la siguiente lista utilizando la coordenada z. 

In [31]:
posiciones_partículas = [[0.35752895193490675, 0.6135850565237939, 0.5541585823711876], [0.1582641435141876, 0.31990753962591545, 0.7777448159041722], [0.011779094936090306, 0.5412893280313622, 0.42207866657758797], [0.9590779485753871, 0.3600699361725057, 0.5874795018642345], [0.15471222881030555, 0.6187076130627565, 0.641038092495203], [0.41888995576478893, 0.546646019774619, 0.012553988948035277], [0.008843578551037679, 0.25460786547164216, 0.09978474497856626], [0.34249106661331674, 0.9583919742837403, 0.7424025656582383], [0.05294112640186133, 0.03204461728958852, 0.12312307343748374], [0.6508649534794841, 0.8870182278555627, 0.8940793294792357], [0.47244251797632475, 0.05926652975809854, 0.08528041740276704], [0.19897324408398576, 0.810799386411295, 0.44697854262896297], [0.20005522309028967, 0.5407288463534208, 0.011469849647589792], [0.6050901075520663, 0.4924266661109089, 0.18630478314249888], [0.4476357868456178, 0.3650347430903953, 0.016165344006425553], [0.4388710300534895, 0.08957879215713072, 0.04722273783305231], [0.6761239107439847, 0.5594163544819675, 0.5462660382013711], [0.4601817318708574, 0.28348184524771125, 0.373613152603256], [0.5480864230608407, 0.13182826757958255, 0.2711250583834848], [0.5557897561886886, 0.09360049213238564, 0.7093853233603227], [0.46838349455426975, 0.28984367833974845, 0.3564254615477773], [0.6270199952355979, 0.7855464323332317, 0.00815664803773175], [0.8555450803316107, 0.7173135955108818, 0.3222121107933902], [0.7855840958866223, 0.731933077479366, 0.6804336780099915], [0.7336047585226249, 0.11427329443477374, 0.5839677193611523], [0.7954702420504332, 0.7201322124329799, 0.5904551286127606], [0.426873299289279, 0.6443664197903036, 0.3151552929687049], [0.7138481301537845, 0.4591602188918029, 0.3043711424237865], [0.6153825309441929, 0.9308043807791899, 0.20201720306867355], [0.7888136202660068, 0.8304683883624902, 0.3684275157526047], [0.5000087279222996, 0.923992785245564, 0.9593534571630875], [0.4020839101063509, 0.9933510105076713, 0.3142788117746256], [0.004171711393455402, 0.4483607978770878, 0.5588262479384252], [0.4944030692878052, 0.24875984042019605, 0.32619838077281704], [0.5574807815514278, 0.3774741819098111, 0.038997566094574276], [0.6265471168679924, 0.917758458471198, 0.903939471046953], [0.45365109223940436, 0.09281675333650385, 0.751672757231582], [0.6166722256944308, 0.3865309650598896, 0.4662477519478403], [0.589128684441947, 0.0222544341415305, 0.6299427947467198], [0.454827718400453, 0.6918107168523762, 0.5297498355144554], [0.37773051976989436, 0.4820310733694275, 0.9437554419595358], [0.4732180821271623, 0.4200494146874252, 0.20420935650431193], [0.44978118571699177, 0.6983891244048497, 0.9973242496988164], [0.281072568748969, 0.11598343710222947, 0.5052828930489315], [0.6797116447968055, 0.20156196961333483, 0.878498761476677], [0.34794168569369965, 0.8021851639352973, 0.4238002404558674], [0.04689922292672932, 0.9036197866530675, 0.8353735672247944], [0.7564256995447107, 0.969990004246863, 0.31097320844195186], [0.6574840750585511, 0.16631255077155993, 0.7919694287453942], [0.9589493225246419, 0.8865986613385679, 0.8161471202205446], [0.5640281175403634, 0.09275142069378695, 0.2556778100549657], [0.6001838786344198, 0.8175009432465357, 0.11415061550337735], [0.24182562095086957, 0.6755991617059631, 0.04509690308618364], [0.12435476380147081, 0.47451630777372333, 0.8894962445365153], [0.379395395531803, 0.5546064940543587, 0.26539645269363366], [0.6766197059901027, 0.9361700562587805, 0.9822582266409405], [0.8290623075269421, 0.07580800954737366, 0.18276214188804119], [0.10202476159425533, 0.634387495848362, 0.6564495459319641], [0.9850393395873172, 0.8881149778238648, 0.13657706269068615], [0.2972048166520307, 0.173964838872525, 0.29082528370120775], [0.04351858032047162, 0.5412001330195615, 0.9931653909939158], [0.583167792258082, 0.03714308726644355, 0.6197344386425849], [0.4483272716869955, 0.9417762415255244, 0.1636133996835032], [0.08737621471096757, 0.507884290705463, 0.8592242842390598], [0.30781767773153446, 0.7634368415756658, 0.48774768441596184], [0.5906735674044528, 0.13550903564502237, 0.6821897701707209], [0.5542245329529807, 0.345175793833729, 0.9755253119866152], [0.5960459599423442, 0.24183250449050298, 0.31067380087078966], [0.34341427035060645, 0.5514556968704987, 0.49445746172943905], [0.16836044620498325, 0.7725024131748883, 0.6124589722921168], [0.7171428683633372, 0.30099948984707625, 0.07210849682054099], [0.9241380378958883, 0.8406021788318481, 0.8454229703952914], [0.36503494181998786, 0.3448082311505789, 0.5766313219264323], [0.9500062059874412, 0.775230199864728, 0.5564978844020652], [0.34471329318999366, 0.29190609382205546, 0.6412197052748692], [0.29586800097779875, 0.42592291999656684, 0.42923856259250304], [0.10494524557637219, 0.06263766787632075, 0.33190282691497575], [0.27607274852482244, 0.08829132332273781, 0.5148876558036883], [0.9386640518128488, 0.2679446540205377, 0.505814406723242], [0.3231795203706196, 0.7276002191278976, 0.29436177313823997], [0.7180654061294991, 0.7505062700202454, 0.3665657898974164], [0.26377322438348627, 0.6591457119199864, 0.026374500398246292], [0.7403677182382848, 0.26124159311720807, 0.9300705160081932], [0.2436422313974076, 0.6830185788699146, 0.38558241368091317], [0.4472866531577959, 0.41233841645561387, 0.9734752604895842], [0.7929266263089931, 0.1794896069121723, 0.26352842582055946], [0.037455844474381994, 0.6207616275544798, 0.012690786846818902], [0.552797276841932, 0.5208698077961844, 0.9582235496217077], [0.1043359022887893, 0.8244448149064594, 0.607566011067759], [0.928429716481322, 0.8417711980956548, 0.500469600137839], [0.9269761073004832, 0.34885040727093286, 0.2528841657574865], [0.37092770283803445, 0.5494452520225197, 0.9488640284341445], [0.35417156860279864, 0.11155278360707066, 0.5770376037871334], [0.6170716012029482, 0.07621683310270022, 0.506916893380182], [0.8491035824241289, 0.8159682609541095, 0.9542773080572016], [0.9089094567408531, 0.4227095264027776, 0.5194417317897557], [0.8514977803894932, 0.2831170415429094, 0.030118398694616744], [0.36171732294663883, 0.10629236891237981, 0.4321635582879222], [0.6985045386980713, 0.45049094024737757, 0.7860567676970855], [0.7937696138605588, 0.3778023725565889, 0.28137701956163363]]

100-element Vector{Vector{Float64}}:
 [0.35752895193490675, 0.6135850565237939, 0.5541585823711876]
 [0.1582641435141876, 0.31990753962591545, 0.7777448159041722]
 [0.011779094936090306, 0.5412893280313622, 0.42207866657758797]
 [0.9590779485753871, 0.3600699361725057, 0.5874795018642345]
 [0.15471222881030555, 0.6187076130627565, 0.641038092495203]
 [0.41888995576478893, 0.546646019774619, 0.012553988948035277]
 [0.008843578551037679, 0.25460786547164216, 0.09978474497856626]
 [0.34249106661331674, 0.9583919742837403, 0.7424025656582383]
 [0.05294112640186133, 0.03204461728958852, 0.12312307343748374]
 [0.6508649534794841, 0.8870182278555627, 0.8940793294792357]
 [0.47244251797632475, 0.05926652975809854, 0.08528041740276704]
 [0.19897324408398576, 0.810799386411295, 0.44697854262896297]
 [0.20005522309028967, 0.5407288463534208, 0.011469849647589792]
 ⋮
 [0.1043359022887893, 0.8244448149064594, 0.607566011067759]
 [0.928429716481322, 0.8417711980956548, 0.500469600137839]
 [0.9269761

In [32]:
sort(posiciones_partículas, by = x-> x[3])

100-element Vector{Vector{Float64}}:
 [0.6270199952355979, 0.7855464323332317, 0.00815664803773175]
 [0.20005522309028967, 0.5407288463534208, 0.011469849647589792]
 [0.41888995576478893, 0.546646019774619, 0.012553988948035277]
 [0.037455844474381994, 0.6207616275544798, 0.012690786846818902]
 [0.4476357868456178, 0.3650347430903953, 0.016165344006425553]
 [0.26377322438348627, 0.6591457119199864, 0.026374500398246292]
 [0.8514977803894932, 0.2831170415429094, 0.030118398694616744]
 [0.5574807815514278, 0.3774741819098111, 0.038997566094574276]
 [0.24182562095086957, 0.6755991617059631, 0.04509690308618364]
 [0.4388710300534895, 0.08957879215713072, 0.04722273783305231]
 [0.7171428683633372, 0.30099948984707625, 0.07210849682054099]
 [0.47244251797632475, 0.05926652975809854, 0.08528041740276704]
 [0.008843578551037679, 0.25460786547164216, 0.09978474497856626]
 ⋮
 [0.6265471168679924, 0.917758458471198, 0.903939471046953]
 [0.7403677182382848, 0.26124159311720807, 0.9300705160081932]

[12] **(dificultad media)** Busca información sobre la función "findall" usando ?. Quita los acentos del texto del problema 9 (para trabajar con acentos hay que hacer algo especial que veremos después). Utiliza la función findall para encontrar todos los espacios vacíos del texto. Finalmente haz un arreglo que contenga como elementos cada una de las palabras del texto. Es decir, que texto[1] = Este, texto[2] = texto, ... texto[end] = distancia.

Si quieres lucirte asegúrate que las palabras no contengan signos de puntuación o paréntesis. 

En la siguiente celda está el texto del ejercicio 9 sin acentos, signos de puntuación ni paréntesis

In [34]:
texto = "Este texto no lo entiende cualquera solamente dando el arreglo fijado vereis el mensaje oculto aqui Si crees que con magia puedes encontrar el mensaje escondido no estaras mal Saber programar no es saber magia sea lo que sea que eso signifique pero para muchos lo que lograran sera casi como magia blanca de esa que solo se usa para el bien Puedes por ejemplo diagnosticar una enfermedad sin conocer de medicina o predecir el clima incluso puedes controlar aparatos a kilometros de distancia"

"Este texto no lo entiende cualquera solamente dando el arreglo fijado vereis el mensaje oculto aqui Si crees que con magia puedes encontrar el mensaje escondido no estaras mal Saber programar no es saber magia sea lo que sea que eso signifique pero para muchos lo que lograran sera casi como magia blanca de esa que solo se usa para el bien Puedes por ejemplo diagnosticar una enfermedad sin conocer de medicina o predecir el clima incluso puedes controlar aparatos a kilometros de distancia"

In [35]:
espacios = findall(" ",texto)

83-element Vector{UnitRange{Int64}}:
 5:5
 11:11
 14:14
 17:17
 26:26
 36:36
 46:46
 52:52
 55:55
 63:63
 70:70
 77:77
 80:80
 ⋮
 412:412
 414:414
 423:423
 426:426
 432:432
 440:440
 447:447
 457:457
 466:466
 468:468
 479:479
 482:482

In [36]:
#palabras = [texto[1:4],texto[6:10], texto[12:13]]                                                                                           }
#palabras[1]                                                                                                                                 }--> Esbozo de la función
#palabras = [texto[1:espacios[1][1]-1] , texto[(espacios[1][1]+1) : (espacios[2][1]-1)] , texto[(espacios[2][1]+1) : (espacios[3][1]-1)]]    } 

j(x) = texto[(espacios[x][1]+1) : (espacios[x+1][1]-1)]

#=
j(1)                                                       }
j(2)                                                       }---> Prueba de la función
j(3)     # j(i) nos da la i+1-esima palabra de _texto_     } 
=#

palabras = [j(i) for i in 1:82]       # Arreglo casi final utilizando la función (faltan la primera y última palabra)     

82-element Vector{String}:
 "texto"
 "no"
 "lo"
 "entiende"
 "cualquera"
 "solamente"
 "dando"
 "el"
 "arreglo"
 "fijado"
 "vereis"
 "el"
 "mensaje"
 ⋮
 "medicina"
 "o"
 "predecir"
 "el"
 "clima"
 "incluso"
 "puedes"
 "controlar"
 "aparatos"
 "a"
 "kilometros"
 "de"

In [37]:
palabras1 = append!(["Este"], palabras)
palabras_final = append!(palabras1, ["distancia"])   # Arreglo final :) 

84-element Vector{String}:
 "Este"
 "texto"
 "no"
 "lo"
 "entiende"
 "cualquera"
 "solamente"
 "dando"
 "el"
 "arreglo"
 "fijado"
 "vereis"
 "el"
 ⋮
 "o"
 "predecir"
 "el"
 "clima"
 "incluso"
 "puedes"
 "controlar"
 "aparatos"
 "a"
 "kilometros"
 "de"
 "distancia"

[13] **(dificultad media)** Con el arreglo del problema anterior obten una lista de las frecuencias con las que aparece cada palabra del texto (no puedes usar ciclos, es decir, for, while, ni el condicional if o ?) y otra lista que contenga a qué palabra corresponde cada frecuencia. 

Aunque no es necesario para la tarea, pruébalo con otros textos (por ejemplo con conversaciones que tengas con amigos o correos ¿qué palabras usan más? 

In [38]:
frecuencia = ([findall(palabras_final[i],texto) for i in 1:84])

84-element Vector{Vector{UnitRange{Int64}}}:
 [1:4]
 [6:10]
 [12:13, 162:163, 193:194, 365:366, 395:396]
 [15:16, 61:62, 215:216, 262:263, 269:270, 319:320, 358:359, 471:472]
 [18:25]
 [27:35]
 [37:45]
 [47:51]
 [53:54, 78:79, 141:142, 334:335, 424:425]
 [56:62]
 [64:69]
 [71:76]
 [53:54, 78:79, 141:142, 334:335, 424:425]
 ⋮
 [10:10, 13:13, 16:16, 38:38, 51:51, 62:62, 69:69, 89:89, 94:94, 115:115  …  366:366, 394:394, 396:396, 413:413, 439:439, 449:449, 453:453, 464:464, 472:472, 477:477]
 [415:422]
 [53:54, 78:79, 141:142, 334:335, 424:425]
 [427:431]
 [433:439]
 [124:129, 441:446]
 [448:456]
 [458:465]
 [29:29, 35:35, 40:40, 48:48, 56:56, 67:67, 85:85, 96:96, 119:119, 122:122  …  386:386, 411:411, 431:431, 455:455, 458:458, 460:460, 462:462, 467:467, 487:487, 491:491]
 [469:478]
 [24:25, 127:128, 306:307, 345:346, 401:402, 418:419, 444:445, 480:481]
 [483:491]

In [39]:
frecuencia1 = [length(frecuencia[i]) for i in 1:84]

84-element Vector{Int64}:
  1
  1
  5
  8
  1
  1
  1
  1
  5
  1
  1
  1
  5
  ⋮
 38
  1
  5
  1
  1
  2
  1
  1
 50
  1
  8
  1

In [40]:
frecuencia_palabra = [[palabras_final[i],frecuencia1[i]] for i in 1:84]

84-element Vector{Vector{Any}}:
 ["Este", 1]
 ["texto", 1]
 ["no", 5]
 ["lo", 8]
 ["entiende", 1]
 ["cualquera", 1]
 ["solamente", 1]
 ["dando", 1]
 ["el", 5]
 ["arreglo", 1]
 ["fijado", 1]
 ["vereis", 1]
 ["el", 5]
 ⋮
 ["o", 38]
 ["predecir", 1]
 ["el", 5]
 ["clima", 1]
 ["incluso", 1]
 ["puedes", 2]
 ["controlar", 1]
 ["aparatos", 1]
 ["a", 50]
 ["kilometros", 1]
 ["de", 8]
 ["distancia", 1]

In [41]:
frecuencia_final = unique(sort(frecuencia_palabra, by = x -> x[2], rev = true))

64-element Vector{Vector{Any}}:
 ["a", 50]
 ["o", 38]
 ["es", 9]
 ["lo", 8]
 ["de", 8]
 ["que", 7]
 ["no", 5]
 ["el", 5]
 ["con", 5]
 ["se", 4]
 ["magia", 3]
 ["para", 3]
 ["mensaje", 2]
 ⋮
 ["una", 1]
 ["enfermedad", 1]
 ["sin", 1]
 ["conocer", 1]
 ["medicina", 1]
 ["predecir", 1]
 ["clima", 1]
 ["incluso", 1]
 ["controlar", 1]
 ["aparatos", 1]
 ["kilometros", 1]
 ["distancia", 1]

[14] **(fácil)** Obtén el área del paralelogramo formado por los vectores: $(1,1/2)$ y $(\sqrt{3},1)$. 

In [42]:
using LinearAlgebra
A = [1,1/2,0]
B = [√(3),1,0]
C = cross(A,B)
norm(C)

0.1339745962155614

[15] **(fácil)** resuelve el siguiente sistema de ecuaciones numéricamente: 

$$ x_1 + x_2 = 2, $$
$$ x_2 - x_3 = 1.1$$
$$ 2x_4 + x_2 - 2x_3 = i$$
$$ x_1 + x_2 - 2x_4 = -i$$


Si $A\vec{x}=\vec{b}$, entonces $\vec{x}=A^{-1}\vec{b}$ 

In [45]:
A = [1 1 0 0 ; 0 1 -1 0 ; 0 1 -2 2; 1 1 0 -2]
b = [2, 1.1, im, -im]

X = *(inv(A),b)

4-element Vector{ComplexF64}:
 -2.2 + 0.0im
  4.2 + 0.0im
  3.1 + 0.0im
  1.0 + 0.5im

[16] **(fácil)** Explica la diferencia entre sin(A) y sin.(A) si A es una matriz. 

Consideremos $A$ la siguiente matriz $A=\pmatrix{1 & 1 \\ 1 & 1}$

In [52]:
A=[1 1;1 1]
println(sin(1))
println(sin(A))
println(sin.(A))

0.8414709848078965
[0.4546487134128408 0.4546487134128408; 0.4546487134128408 0.4546487134128408]
[0.8414709848078965 0.8414709848078965; 0.8414709848078965 0.8414709848078965]


Se puede observar que $sin.(A)$ calcula el seno de cada entrada de la matriz, mientras que $sin(A)$ se define como $sin(tA)=\sum_{k=0}^{\infty}\frac{(-1)^k(tA)^{2k+1}}{(2k+1)!}$

[17] **(fácil)** Obtén los egenvalores y eigenvectores del sistema del problema 15. 

In [53]:
A = [1 1 0 0 ; 0 1 -1 0 ; 0 1 -2 2; 1 1 0 -2]
eigvals(A)

4-element Vector{ComplexF64}:
 -2.5115471416945354 + 0.0im
 -1.0000000000000002 + 0.0im
  0.7557735708472664 - 0.4744767780073265im
  0.7557735708472664 + 0.4744767780073265im

In [56]:
eigvecs(A)

4×4 Matrix{ComplexF64}:
 -0.0726454+0.0im   0.213201+0.0im  …   0.825429+0.0im
   0.255098+0.0im  -0.426401+0.0im     -0.201592+0.391647im
   0.895788+0.0im  -0.852803+0.0im      0.136593+0.191301im
  -0.356668+0.0im  -0.213201+0.0im      0.243622+0.100173im

[18] **(fácil)** Escribe una matriz de rotación cualquiera en 3D. Obtén sus eigenvectores y eigenvalores. ¿Qué significan? 

In [67]:
θ = π / 8
B = [1 0 0;0 cos(θ) -sin(θ);0 sin(θ) cos(θ)]
println(eigvecs(B))
println(eigvals(B))

ComplexF64[0.0 - 0.0im 0.0 + 0.0im 1.0 + 0.0im; 0.0 - 0.7071067811865475im 0.0 + 0.7071067811865475im 0.0 + 0.0im; 0.7071067811865476 - 0.0im 0.7071067811865476 + 0.0im 0.0 + 0.0im]
ComplexF64[0.9238795325112867 - 0.3826834323650897im, 0.9238795325112867 + 0.3826834323650897im, 1.0 + 0.0im]


[19] **(fácil)** Matrices de colores: Instala la paqueteria Colors. Para esto escribe en la linea de compandos

] add Colors

Carga la paquetería Colors después de instalada. Esta paquetería la veremos en videos más adelante. Por ahora solo jugaremos un poco con la función RGB. RGB(x,y,z) arroja el color de mezclar una cantidad x de rojo, una y de verde y una z de azul. x,y y z están entre 0 y 1. 

Haz una matriz que contenga como elementos RGB(x,1-x,z), para unos 20 valores de x y unos 200 valores de z. 

In [70]:
] add Colors

   Resolving package versions...
  No Changes to `~/.julia/environments/v1.6/Project.toml`
  No Changes to `~/.julia/environments/v1.6/Manifest.toml`


In [77]:
using Colors

In [78]:
RGB(.5,.3,.6)

In [80]:
Matriz_RGB = [RGB(i,1-i,j) for i in rand(20),j in rand(200)]

[20] **(difícil)** Haz una matriz $Amigos$ de  $1000 \times 1000$ cuyos elementos $Amigos_{i,j}$ sea igual a $1$ si $i$ y $j$ son números amigos y sea igual a $0$ en otro caso. 

Nota: Los números amigos son aquellos donde la suma de sus divisores es igual al otro número (revisar wikipedia para ejemplos). 

Nota2: Recuerda que no puedes usar if, o crear funciones de más de 1 linea. Sí puedes crear funciones como f(x) = x^2. 

In [82]:
using LinearAlgebra
Divisores_propios = Int.([(i % j) == 0 for i in 1:1000, j in 1:1000] .* [(i/j) for i in 1:1000, j in 1:1000])  
#la primer matriz nos indica el lugar donde hay divisores propios y la segunda el valor de estos (se sugiere probar cada matriz por separado para ver mejor lo que contiene c/u)

1000×1000 Matrix{Int64}:
    1    0    0    0    0    0    0  …  0  0  0  0  0  0  0  0  0  0  0  0
    2    1    0    0    0    0    0     0  0  0  0  0  0  0  0  0  0  0  0
    3    0    1    0    0    0    0     0  0  0  0  0  0  0  0  0  0  0  0
    4    2    0    1    0    0    0     0  0  0  0  0  0  0  0  0  0  0  0
    5    0    0    0    1    0    0     0  0  0  0  0  0  0  0  0  0  0  0
    6    3    2    0    0    1    0  …  0  0  0  0  0  0  0  0  0  0  0  0
    7    0    0    0    0    0    1     0  0  0  0  0  0  0  0  0  0  0  0
    8    4    0    2    0    0    0     0  0  0  0  0  0  0  0  0  0  0  0
    9    0    3    0    0    0    0     0  0  0  0  0  0  0  0  0  0  0  0
   10    5    0    0    2    0    0     0  0  0  0  0  0  0  0  0  0  0  0
   11    0    0    0    0    0    0  …  0  0  0  0  0  0  0  0  0  0  0  0
   12    6    4    3    0    2    0     0  0  0  0  0  0  0  0  0  0  0  0
   13    0    0    0    0    0    0     0  0  0  0  0  0  0  0  0  0  0  0


In [83]:
Divisores_propios1 = Divisores_propios[2:1000,2:1000]  #le quitamos la primer columna y primer renglón para hacer más fáciles los cálculos

999×999 Matrix{Int64}:
   1    0    0    0    0    0    0  …  0  0  0  0  0  0  0  0  0  0  0  0
   0    1    0    0    0    0    0     0  0  0  0  0  0  0  0  0  0  0  0
   2    0    1    0    0    0    0     0  0  0  0  0  0  0  0  0  0  0  0
   0    0    0    1    0    0    0     0  0  0  0  0  0  0  0  0  0  0  0
   3    2    0    0    1    0    0     0  0  0  0  0  0  0  0  0  0  0  0
   0    0    0    0    0    1    0  …  0  0  0  0  0  0  0  0  0  0  0  0
   4    0    2    0    0    0    1     0  0  0  0  0  0  0  0  0  0  0  0
   0    3    0    0    0    0    0     0  0  0  0  0  0  0  0  0  0  0  0
   5    0    0    2    0    0    0     0  0  0  0  0  0  0  0  0  0  0  0
   0    0    0    0    0    0    0     0  0  0  0  0  0  0  0  0  0  0  0
   6    4    3    0    2    0    0  …  0  0  0  0  0  0  0  0  0  0  0  0
   0    0    0    0    0    0    0     0  0  0  0  0  0  0  0  0  0  0  0
   7    0    0    0    0    2    0     0  0  0  0  0  0  0  0  0  0  0  0
   ⋮           

In [84]:
suma_DP = [sum(Divisores_propios1[i,:]) for i in 1:999]    #La suma de los divisores propios desde el 2 hasta el 1000

999-element Vector{Int64}:
    1
    1
    3
    1
    6
    1
    7
    4
    8
    1
   16
    1
   10
    ⋮
   67
 1818
    1
 1024
  335
  734
  205
 1356
    1
  502
  521
 1340

In [85]:
lista1 = [[(i+1) , suma_DP[i]] for i in 1:999]    #Duplas del número y la suma de sus divisores propios

999-element Vector{Vector{Int64}}:
 [2, 1]
 [3, 1]
 [4, 3]
 [5, 1]
 [6, 6]
 [7, 1]
 [8, 7]
 [9, 4]
 [10, 8]
 [11, 1]
 [12, 16]
 [13, 1]
 [14, 10]
 ⋮
 [989, 67]
 [990, 1818]
 [991, 1]
 [992, 1024]
 [993, 335]
 [994, 734]
 [995, 205]
 [996, 1356]
 [997, 1]
 [998, 502]
 [999, 521]
 [1000, 1340]

In [86]:
lista2 = [[suma_DP[i] , (i+1)] for i in 1:999]   #Las mismas duplas pero en el orden contrario

999-element Vector{Vector{Int64}}:
 [1, 2]
 [1, 3]
 [3, 4]
 [1, 5]
 [6, 6]
 [1, 7]
 [7, 8]
 [4, 9]
 [8, 10]
 [1, 11]
 [16, 12]
 [1, 13]
 [10, 14]
 ⋮
 [67, 989]
 [1818, 990]
 [1, 991]
 [1024, 992]
 [335, 993]
 [734, 994]
 [205, 995]
 [1356, 996]
 [1, 997]
 [502, 998]
 [521, 999]
 [1340, 1000]

In [87]:
num_am = [lista1[i] == lista2[j] for i in 1:999, j in 1:999]    #Se buscan duplas iguales (lo que representaría que encontramos numeros amigos)

999×999 Matrix{Bool}:
 0  0  0  0  0  0  0  0  0  0  0  0  0  …  0  0  0  0  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  0  0  0  0  0     0  0  0  0  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  0  0  0  0  0     0  0  0  0  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  0  0  0  0  0     0  0  0  0  0  0  0  0  0  0  0  0
 0  0  0  0  1  0  0  0  0  0  0  0  0     0  0  0  0  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  0  0  0  0  0  …  0  0  0  0  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  0  0  0  0  0     0  0  0  0  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  0  0  0  0  0     0  0  0  0  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  0  0  0  0  0     0  0  0  0  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  0  0  0  0  0     0  0  0  0  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  0  0  0  0  0  …  0  0  0  0  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  0  0  0  0  0     0  0  0  0  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  0  0  0  0  0    

In [88]:
A1 = [ Int.(zeros(1,999)) ;(num_am)]
Matriz_final = [Int.([1;zeros(999,1)]) A1]                    #por último se añaden la primera columna y el primer renglón (sabemos que el 1 es solamente amigo de sí mismo) 

1000×1000 Matrix{Int64}:
 1  0  0  0  0  0  0  0  0  0  0  0  0  …  0  0  0  0  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  0  0  0  0  0     0  0  0  0  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  0  0  0  0  0     0  0  0  0  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  0  0  0  0  0     0  0  0  0  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  0  0  0  0  0     0  0  0  0  0  0  0  0  0  0  0  0
 0  0  0  0  0  1  0  0  0  0  0  0  0  …  0  0  0  0  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  0  0  0  0  0     0  0  0  0  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  0  0  0  0  0     0  0  0  0  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  0  0  0  0  0     0  0  0  0  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  0  0  0  0  0     0  0  0  0  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  0  0  0  0  0  …  0  0  0  0  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  0  0  0  0  0     0  0  0  0  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  0  0  0  0  0 

Ahora veamos quiénes son números amigos

In [89]:
findall(isodd,Matriz_final)   #Buscamos los numeros impares en la matriz (solo hay 0s y 1s)

6-element Vector{CartesianIndex{2}}:
 CartesianIndex(1, 1)
 CartesianIndex(6, 6)
 CartesianIndex(28, 28)
 CartesianIndex(284, 220)
 CartesianIndex(220, 284)
 CartesianIndex(496, 496)